name: 'Sonar Cloud composite action to analyze .NET projects'
description: 'Process .NET test results'
inputs:
  projects:  
    description: 'comma separated list of projects to analyze'
    required: true
  dotnet-version:
    description: 'the .NET version to use with .NET Setup'
    required: true
    default: '7.0.x'
runs:
  using: 'composite'
  steps:
  - name: 'Pre-action checks'
    shell: powershell
    run: |
      $projectArray = "${{ inputs.projects}}".Split(",")
      #check if the action is being run with a Windows runner
      echo "$($projectArray.Length) projects found"
      for ($i = 0; $i -lt $projectArray.Length; $i++)
      {
         echo "Project found: $($projectArray[$i])"
      }
      echo "Runner os: ${{ runner.os }}"
      if ("${{ runner.os }}" -ne 'Windows')
      {
        echo "This composite action currently only supports Windows runners. Linux is coming soon - probably"
        #exit 1
      }
