name: Sonar Cloud composite action to analyze .NET projects
description: 'Process .NET test results'
inputs:
  projects:  # file name of the trx/xml file to process
    description: 'comma separated list of projects to analyze'
    required: true
  dotnet-version:
    description: 'the .NET version to use with .NET Setup'
    required: true
    default: 7.0.x
runs:
  using: composite
  steps:
    - name: Pre-action checks
      shell: pwsh
      run: |
        $projectArray = "${{ inputs.fileName}}".Split(",")
        #check if the action is being run with a Windows runner
        echo "$($projectArray.Length) projects found"
        for ($i = 0; $i -lt $projectArray.Length; $i++)
        {
           write-host "Project found: $($projectArray[$i])"
        }
        echo "Runner os: ${{ runner.os }}"
        if ("${{ runner.os }}" -ne 'Windows')        
        {
          echo "This composite action currently only supports Windows runners. Linux is coming soon - probably"
          #exit 1
        }
  
