name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: # https://stackoverflow.com/questions/59175332/using-output-from-a-previous-job-in-a-new-one-in-a-github-action
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}  
    steps:    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 #fetch-depth is needed for GitVersion
          #Install and calculate the new version with GitVersion          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: 5.x
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.10.2
        id: gitversion # step id used as reference for output values
      - name: Display GitVersion outputs
        run: |
          echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
          
          
  windowsTest: 
    runs-on: windows-latest
    steps:    
      - name: checkout the code from this branch
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}
      - name: Test this action
        uses: ./ # the ./ runs the action.yml in this repo 
        with:
          projects: 'Sample\ConsoleApp1\ConsoleApp1.csproj'
          dotnet-version: '7.0.x'
          sonarcloud-organization: samsmithnz-github
          sonarcloud-project: samsmithnz_SamsDotNetSonarCloudAction
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  linuxTest: 
    runs-on: ubuntu-latest
    steps:    
      - name: checkout the code from this branch
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}
      - name: Test this action
        uses: ./ # the ./ runs the action.yml in this repo 
        with:
          projects: 'Sample/ConsoleApp1/ConsoleApp1.csproj'
          dotnet-version: '7.0.x'
          sonarcloud-organization: samsmithnz-github
          sonarcloud-project: samsmithnz_SamsDotNetSonarCloudAction
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  release:
    runs-on: windows-latest
    needs: 
    - build      
    - windowsTest
    - linuxTest
    if: github.ref == 'refs/heads/main'
    steps:   
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ needs.build.outputs.Version }}" 
        echo "CommitsSinceVersionSource: ${{ needs.build.outputs.CommitsSinceVersionSource }}" 
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: needs.build.outputs.CommitsSinceVersionSource > 0 #Only create a release if there has been a commit/version change
      with:
        tag: "v${{ needs.build.outputs.Version }}"
        name: "v${{ needs.build.outputs.Version }}"
        token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
